backend:
  name: git-gateway
  branch: master

media_folder: 'static/assets'
public_folder: '/assets'

site_url: https://mystifying-bartik-329370.netlify.com

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'static/content/home.md'
        fields:
          - { label: 'Page Title', name: pageTitle, widget: string }
          - { label: 'Hero Title', name: heroTitle, widget: string }
          - { label: 'Hero Subtitle', name: heroSubtitle, widget: string }
          - {
              label: 'Hero Image',
              name: heroImage,
              required: false,
              widget: image,
            }
          - {
              defaultValue: 100,
              label: 'Hero Image Opacity',
              max: 100,
              min: 0,
              name: 'heroImageOpacityHomePage',
              required: false,
              step: 5,
              valueType: 'int',
              widget: 'number',
            }
          - {
              label: 'Hero Buttons',
              name: 'heroButtonsHomePage',
              widget: 'object',
              fields:
              - label: 'Résumé Button',
                name: 'resumeButton',
                widget: 'object',
                fields:
                - label: 'Label',
                  name: 'label',
                  widget: 'string',
                - label: 'Link',
                  name: 'link',
                  widget: 'string',
              - label: 'Contact Button',
                name: 'contactButton',
                widget: 'object',
                fields:
                - label: 'Label',
                  name: 'label',
                  widget: 'string',
                - label: 'Link',
                  name: 'link',
                  widget: 'string',
            }
          - {
              label: 'About Me Title',
              name: aboutMeSectionTitle,
              widget: string,
            }
          - {
              label: 'About Me Body',
              name: aboutMeSectionBody,
              widget: markdown,
            }
          - {
              label: 'Skills Section Title',
              name: skillsSectionTitle,
              widget: string,
            }
          - {
              label: 'Skills Search Label',
              name: skillsSearchLabel,
              widget: string,
            }
          - {
              label: 'Skills Search Name',
              name: skillsSearchName,
              widget: string,
            }
          - {
              label: 'Skills Search Placeholder',
              name: skillsSearchPlaceholder,
              widget: string,
            }
          - { label: 'Skill Not Found', name: skillNotFound, widget: string }
          - label: Skills Sections List
            label_singular: Skills List
            name: skillsSectionList
            name_singular: skillsList
            widget: list
            fields:
              - { label: 'Section Label', name: sectionLabel, widget: string }
              - label: Skills List
                name: skillsList
                widget: list
                fields:
                  - { label: 'Icon', name: icon, widget: string }
                  - { label: 'Label', name: label, widget: string }
      - label: 'Portfolio Page'
        name: 'portfolio'
        file: 'static/content/portfolio.md'
        fields:
          - { label: 'Page Title', name: pageTitle, widget: string }
          - { label: 'View Project CTA', name: viewProjectCTA, widget: string }
          - {
              label: 'Hero Image',
              name: heroImagePortfolioPage,
              required: false,
              widget: image,
            }
          - {
              defaultValue: 100,
              label: 'Hero Image Opacity',
              max: 100,
              min: 0,
              name: 'heroImageOpacityPortfolioPage',
              required: false,
              step: 5,
              valueType: 'int',
              widget: 'number',
            }
      - label: 'Project Page'
        name: 'project'
        file: 'static/content/project.md'
        fields:
          - {
              label: 'Return Button Image',
              name: returnButtonImage,
              widget: image,
            }
      - label: 'Contact Page'
        name: 'contact'
        file: 'static/content/contact.md'
        fields:
          - { label: 'Page Title', name: pageTitle, widget: string }
          - {
              label: 'Hero Image',
              name: heroImageContactPage,
              required: false,
              widget: image,
            }
          - {
              defaultValue: 100,
              label: 'Hero Image Opacity',
              max: 100,
              min: 0,
              name: 'heroImageOpacityContactPage',
              required: false,
              step: 5,
              valueType: 'int',
              widget: 'number',
            }
      - label: '404 Page'
        name: '404'
        file: 'static/content/404.md'
        fields:
          - { label: 'Page Title', name: pageTitle, widget: string }
  - label: 'Globals'
    name: 'globals'
    files:
      - allow_add: true
        label: 'Navigation'
        name: 'navigation'
        file: 'static/content/navigation.md'
        fields:
          - { label: 'Logo Copy', name: headerLogoCopy, widget: string }
          - { label: 'Logo Icon', name: headerLogoIcon, widget: image }
          - label: 'Navigation Links'
            label_singular: 'Navigation Link'
            name: 'navigationLinks'
            widget: 'list'
            fields:
              - { label: 'Page Name', name: pageName, widget: string }
              - { label: 'Page URL', name: pageURL, widget: string }
      - allow_add: true
        label: 'Footer'
        name: 'footer'
        file: 'static/content/footer.md'
        fields:
          - { label: 'Footer Copy', name: 'footerCopy', widget: string }
          - label: 'Social Media Links'
            label_singular: 'Social Media Link'
            name: 'socialMediaLinks'
            widget: 'list'
            fields:
              - {
                  label: 'Social Medium Name',
                  name: socialMediumName,
                  widget: string,
                }
              - {
                  label: 'Social Medium URL',
                  name: socialMediumURL,
                  widget: string,
                }
              - {
                  label: 'Social Medium Icon',
                  name: socialMediumIcon,
                  widget: image,
                }
  - create: true
    folder: static/content/projects
    identifier_field: path
    label: Projects
    label_singular: Project
    name: projects
    fields:
      - { name: path, label: 'Path', widget: string }
      - { name: date, label: 'Date', widget: date }
      - { name: pageTitle, label: 'Page Title', widget: string }
      - { name: title, label: 'Title', widget: string }
      - { name: role, label: 'Role', widget: string }
      - { name: excerpt, label: 'Excerpt', widget: string }
      - { name: projectThumbnail, label: 'Project Thumbnail', widget: image }
      - { name: description, label: 'Description', widget: text }
      - {
          name: sectionTitleTechnology,
          label: 'Section Title: Technology',
          widget: string,
        }
      - {
          name: sectionBodyTechnology,
          label: 'Section Body: Technology',
          widget: markdown,
        }
