backend:
  name: git-gateway
  branch: master

media_folder: 'static/assets'
public_folder: '/assets'

site_url: https://mystifying-bartik-329370.netlify.com

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'static/content/home.md'
        fields:
          - {label: Page Title, name: pageTitle, widget: string}
          - {label: Hero Title, name: heroTitle, widget: string}
          - {label: Hero Image, name: heroImage, widget: image}
