backend:
  name: git-gateway
  branch: master

media_folder: 'static/assets'
public_folder: '/assets'

site_url: https://mystifying-bartik-329370.netlify.com

default_image: &default_image
  label: 'Hero Image Block'
  name: 'heroImageBlock'
  widget: 'object'
  fields:
    - label: 'Image'
      name: 'imageSource'
      widget: 'image'
    - label: 'Title'
      name: 'imageTitle'
      default: ''
      required: false
      widget: 'string'
    - label: 'Alt'
      name: 'imageAlt'
      widget: 'string'
    - label: 'Image Opacity'
      name: 'imageOpacity'
      default: 100
      max: 100
      min: 0
      required: false
      step: 5
      valueType: 'int'
      widget: 'number'

default_seo: &default_seo
  label: 'Page SEO'
  name: 'pageSEO'
  widget: 'object'
  fields:
    - label: 'Page Title'
      name: 'pageTitle'
      required: false
      widget: 'string'
    - label: 'Page Posting Title'
      name: 'pagePostingTitle'
      required: false
      widget: 'string'
    - label: 'Page Description'
      name: 'pageDescription'
      required: false
      widget: 'string'
    - label: 'Page Author'
      name: 'pageAuthor'
      required: false
      widget: 'string'
    - label: 'Page Keywords (Comma-Separated)'
      name: 'pageKeywords'
      required: false
      widget: 'string'
    - label: 'Page Image'
      name: 'pageImage'
      required: false
      widget: 'string'
    - label: 'Page URL'
      name: 'pageSiteURL'
      required: false
      widget: 'string'
    - label: 'Page Type'
      name: 'pageType'
      required: false
      widget: 'string'

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'static/content/home.md'
        fields:
          - { <<: *default_seo }
          - { <<: *default_image }
          - { label: 'Hero Title', name: 'heroTitle', widget: 'string' }
          - { label: 'Hero Subtitle', name: 'heroSubtitle', widget: 'string' }
          - label: 'Herobuttons'
            name: 'heroButtonsHomePage'
            widget: 'object'
            fields:
              - label: 'Résumé Button'
                name: 'resumeButton'
                widget: 'object'
                fields:
                  - label: 'Label'
                    name: 'label'
                    widget: 'string'
                  - label: 'Link'
                    name: 'link'
                    widget: 'string'
              - label: 'Contact Button'
                name: 'contactButton'
                widget: 'object'
                fields:
                  - label: 'Label'
                    name: 'label'
                    widget: 'string'
                  - label: 'Link'
                    name: 'link'
                    widget: 'string'
          - {
              label: 'About Me Title',
              name: 'aboutMeSectionTitle',
              widget: 'string',
            }
          - {
              label: 'About Me Body',
              name: 'aboutMeSectionBody',
              widget: 'markdown',
            }
          - {
              label: 'About Me Image',
              name: 'aboutMeSectionImageBlock',
              <<: *default_image,
            }
          - {
              label: 'Skills Section Title',
              name: 'skillsSectionTitle',
              widget: 'string',
            }
          - {
              label: 'Skills Search Label',
              name: 'skillsSearchLabel',
              widget: 'string',
            }
          - {
              label: 'Skills Search Name',
              name: 'skillsSearchName',
              widget: 'string',
            }
          - {
              label: 'Skills Search Placeholder',
              name: 'skillsSearchPlaceholder',
              widget: 'string',
            }
          - {
              label: 'Skill Not Found',
              name: 'skillNotFound',
              widget: 'string',
            }
          - label: 'Skills Sections List'
            label_singular: 'Skills List'
            name: 'skillsSectionList'
            name_singular: 'skillsList'
            widget: 'list'
            fields:
              - {
                  label: 'Section Label',
                  name: 'sectionLabel',
                  widget: 'string',
                }
              - label: 'Skills List'
                name: 'skillsList'
                widget: 'list'
                fields:
                  - { label: 'Icon', name: 'icon', widget: 'image' }
                  - { label: 'Label', name: 'label', widget: 'string' }
      - label: 'Portfolio Page'
        name: 'portfolio'
        file: 'static/content/portfolio.md'
        fields:
          - { <<: *default_seo }
          - { <<: *default_image }
          - {
              label: 'Project Role Title',
              name: 'projectRoleTitle',
              widget: 'string',
            }
          - {
              label: 'Project Description Title',
              name: 'projectDescriptionTitle',
              widget: 'string',
            }
          - {
              label: 'View Project CTA',
              name: 'viewProjectCTA',
              widget: 'string',
            }
      - label: 'Project Page'
        name: 'project'
        file: 'static/content/project.md'
        fields:
          - {
              label: 'Source Code CTA',
              name: 'sourceCodeCTA',
              widget: 'string',
            }
          - { label: 'Demo CTA', name: 'demoCTA', widget: 'string' }
          - {
              label: 'Download Content CTA',
              name: 'downloadContentCTA',
              widget: 'string',
            }
          - {
              label: 'Return Button Icon',
              name: 'returnButtonIcon',
              widget: 'image',
            }
      - label: 'Contact Page'
        name: 'contact'
        file: 'static/content/contact.md'
        fields:
          - { <<: *default_seo }
          - { <<: *default_image }
          - { label: 'Hero Title', name: 'heroTitle', widget: 'string' }
          - { label: 'Contact Card Title', name: 'contactCardTitle', widget: 'string' }
          - label: 'Contact Form Fields'
            label_singular: 'Contact Form Field'
            name: 'contactFormFields'
            widget: 'list'
            fields:
              - { label: 'Field Label', name: 'fieldLabel', widget: 'string' }
              - { label: 'Field Name', name: 'fieldName', widget: 'string' }
              - label: 'Field Type'
                name: 'fieldType'
                widget: 'list'
                options: [
                  'date',
                  'datetime-local',
                  'email',
                  'hidden',
                  'month',
                  'number',
                  'password',
                  'range',
                  'search',
                  'tel',
                  'text',
                  'textarea',
                  'time',
                  'url',
                  'week'
                ]
      - label: '404 Page'
        name: '404'
        file: 'static/content/404.md'
        fields:
          - { label: 'Page Title', name: 'pageTitle', widget: 'string' }
  - label: 'Globals'
    name: 'globals'
    files:
      - allow_add: true
        label: 'Navigation'
        name: 'navigation'
        file: 'static/content/navigation.md'
        fields:
          - { label: 'Logo Copy', name: 'headerLogoCopy', widget: 'string' }
          - { label: 'Logo Icon', name: 'headerLogoIcon', widget: 'image' }
          - label: 'Navigation Links'
            label_singular: 'Navigation Link'
            name: 'navigationLinks'
            widget: 'list'
            fields:
              - { label: 'Page Name', name: 'pageName', widget: 'string' }
              - { label: 'Page URL', name: 'pageURL', widget: 'string' }
      - allow_add: true
        label: 'Footer'
        name: 'footer'
        file: 'static/content/footer.md'
        fields:
          - { label: 'Footer Copy', name: 'footerCopy', widget: 'string' }
          - label: 'Social Media Links'
            label_singular: 'Social Media Link'
            name: 'socialMediaLinks'
            widget: 'list'
            fields:
              - {
                  label: 'Social Medium Name',
                  name: 'socialMediumName',
                  widget: 'string',
                }
              - {
                  label: 'Social Medium URL',
                  name: 'socialMediumURL',
                  widget: 'string',
                }
              - {
                  label: 'Social Medium Icon',
                  name: 'socialMediumIcon',
                  widget: 'image',
                }
  - create: true
    folder: 'static/content/projects'
    identifier_field: 'path'
    label: 'Projects'
    label_singular: 'Project'
    name: 'projects'
    fields:
      - { name: 'path', label: 'Path', widget: 'string' }
      - { <<: *default_seo }
      - { name: 'projectTitle', label: 'Project Title', widget: 'string' }
      - {
          name: 'projectSourceCodeURL',
          label: 'Project Source Code URL',
          required: false,
          widget: 'string',
        }
      - {
          name: 'projectDemoURL',
          label: 'Project Demo URL',
          required: false,
          widget: 'string',
        }
      - {
          name: 'downloadContentURL',
          label: 'Download Content URL',
          required: false,
          widget: 'string',
        }
      - { name: 'role', label: 'Role', widget: 'string' }
      - { name: 'projectDate', label: 'Project Date', widget: 'date' }
      - { name: 'projectExcerpt', label: 'Project Excerpt', widget: 'text' }
      - {
          name: 'projectThumbnailImageBlock',
          label: 'Project Thumbnail Image',
          <<: *default_image,
        }
      - { <<: *default_image }
      - {
          name: 'projectDescription',
          label: 'Project Description',
          widget: 'text',
        }
      - label: 'Project Skills'
        label_singular: 'Project Skill'
        name: 'projectSkillsList'
        widget: 'list'
        fields:
          - { name: 'icon', label: 'Icon', widget: 'image' }
          - { name: 'label', label: 'Label', widget: 'string' }
      - label: 'Project Sections'
        label_singular: 'Project Section'
        name: 'projectSectionList'
        widget: 'list'
        fields:
          - {
              name: 'projectSectionImageBlock',
              label: 'Project Section Image',
              <<: *default_image,
            }
          - {
              name: 'projectSectionTitle',
              label: 'Project Section Title',
              widget: 'string',
            }
          - {
              name: 'projectSectionBody',
              label: 'Project Section Body',
              widget: 'markdown',
            }
