backend:
  name: git-gateway
  branch: master

media_folder: 'static/assets'
public_folder: '/assets'

site_url: https://mystifying-bartik-329370.netlify.com

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'static/content/home.md'
        fields:
          - { label: Page Title, name: pageTitle, widget: string }
          - { label: Hero Title, name: heroTitle, widget: string }
          - { label: Hero Image, name: heroImage, widget: image }
      - label: 'Portfolio Page'
        name: 'portfolio'
        file: 'static/content/portfolio.md'
        fields:
          - { label: Page Title, name: pageTitle, widget: string }
      - label: 'Contact Page'
        name: 'contact'
        file: 'static/content/contact.md'
        fields:
          - { label: Page Title, name: pageTitle, widget: string }
      - label: '404 Page'
        name: '404'
        file: 'static/content/404.md'
        fields:
          - { label: Page Title, name: pageTitle, widget: string }
  - label: 'Globals'
    name: 'globals'
    files:
      - allow_add: true
        label: 'Navigation'
        name: 'navigation'
        file: 'static/content/navigation.md'
        fields:
          - { label: Logo Copy, name: logoCopy, widget: string }
          - label: 'Navigation Links'
            name: 'navigationLinks'
            widget: 'list'
            fields:
              - { label: Page Name, name: pageName, widget: string }
              - { label: Page URL, name: pageURL, widget: string }
      - allow_add: true
        label: 'Footer'
        name: 'footer'
        file: 'static/content/footer.md'
        fields:
          - { label: Footer Copy, name: footerCopy, widget: text }
          - { label: LinkedIn URL, name: linkedInURL, widget: string }
          - { label: GitHub URL, name: gitHubURL, widget: string }
          - {
              label: Stack Overflow URL,
              name: stackOverflowURL,
              widget: string,
            }
