backend:
  name: git-gateway
  branch: master

media_folder: 'static/assets'
public_folder: '/assets'

site_url: https://mystifying-bartik-329370.netlify.com

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'static/content/home.md'
        fields:
          - { label: Page Title, name: pageTitle, widget: string }
          - { label: Hero Title, name: heroTitle, widget: string }
          - { label: Hero Image, name: heroImage, widget: image }
      - label: 'Portfolio Page'
        name: 'portfolio'
        file: 'static/content/portfolio.md'
        fields:
          - { label: Page Title, name: pageTitle, widget: string }
          - { label: Hero Title, name: heroTitle, widget: string }
          - { label: Hero Image, name: heroImage, widget: image }
      - label: 'Contact Page'
        name: 'contact'
        file: 'static/content/contact.md'
        fields:
          - { label: Page Title, name: pageTitle, widget: string }
          - { label: Hero Title, name: heroTitle, widget: string }
          - { label: Hero Image, name: heroImage, widget: image }
