export const BACKGROUND_COLOR_BLUE = 'BACKGROUND_COLOR_BLUE';
export const BACKGROUND_COLOR_GREEN = 'BACKGROUND_COLOR_GREEN';
export const BACKGROUND_COLOR_NEUMORPHIC = 'BACKGROUND_COLOR_NEUMORPHIC';
export const BACKGROUND_COLOR_ORANGE = 'BACKGROUND_COLOR_ORANGE';
export const BACKGROUND_COLOR_RED = 'BACKGROUND_COLOR_RED';
export const BACKGROUND_COLOR_WHITE = 'BACKGROUND_COLOR_WHITE';

export const BACKGROUND_COLORS = [
    BACKGROUND_COLOR_BLUE,
    BACKGROUND_COLOR_GREEN,
    BACKGROUND_COLOR_NEUMORPHIC,
    BACKGROUND_COLOR_ORANGE,
    BACKGROUND_COLOR_RED,
    BACKGROUND_COLOR_WHITE
];
