name: CI/CD - Master

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Install Packages
      - name: Install
        run: npm install

      # Build the website
      - name: Build
        run: npm run build:deploy

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public
